import { getDemoContractParameters, getDemoInvoice, getDemoGenerationData } from '@/lib/demo-data'
import { runValidation, type GenerationData } from '@/lib/validation/engine'
import { ValidationReport } from '@/components/validation/ValidationReport'
import { ValidationResultSchema } from '@/lib/schemas/validation'
import { notFound } from 'next/navigation'
import Link from 'next/link'

export default async function ValidatePage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>
  searchParams: Promise<{ invoice?: string }>
}) {
  const { id } = await params
  const { invoice = 'INV-002' } = await searchParams

  const contract = await getDemoContractParameters(id)
  const invData = await getDemoInvoice(invoice)
  if (!contract || !invData) return notFound()

  const genMonthly = await getDemoGenerationData(id)
  let generation: GenerationData | undefined
  if (genMonthly) {
    const relevant = genMonthly.filter((m: any) => m.month >= invData.period_start.substring(0, 7) && m.month <= invData.period_end.substring(0, 7))
    if (relevant.length > 0) {
      generation = {
        total_kwh: relevant.reduce((s: number, m: any) => s + m.kwh, 0),
        availability_pct: relevant.reduce((s: number, m: any) => s + m.availability_pct, 0) / relevant.length,
        period_start: invData.period_start,
        period_end: invData.period_end
      }
    }
  }

  const rawChecks = runValidation(contract, invData, generation)
  const checks = rawChecks.map((check) => ({
    ...check,
    explanation: check.verdict === 'MATCH' ? 'All amounts match contract terms.' : 'Mock explanation for demo. In production, this is generated by Claude.'
  }))

  const totalGap = checks.reduce((s, c) => s + (c.gap_amount ?? 0), 0)
  const totalOpportunity = checks.reduce((s, c) => s + (c.opportunity_amount ?? 0), 0)
  const hasGaps = checks.some((c) => c.verdict === 'GAP')
  const hasOpportunities = checks.some((c) => c.verdict === 'OPPORTUNITY')

  const result = ValidationResultSchema.parse({
    contract_id: id,
    invoice_id: invoice,
    run_at: new Date().toISOString(),
    checks,
    total_gap_amount: totalGap,
    total_opportunity_amount: totalOpportunity,
    verdict: hasGaps ? 'GAPS_FOUND' : hasOpportunities ? 'REVIEW_REQUIRED' : 'CLEAN',
  })

  return (
    <div className="max-w-5xl mx-auto py-8 px-4 space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-[--color-wolvio-navy]">Validation · {invoice}</h1>
        <div className="flex gap-2">
          {['INV-001', 'INV-002', 'INV-003', 'INV-004', 'INV-005', 'INV-006'].map(inv => (
            <Link key={inv} href={`/contracts/${id}/validate?invoice=${inv}`} className={`px-3 py-1 rounded text-sm ${invoice === inv ? 'bg-[--color-wolvio-navy] text-white' : 'bg-[--color-mid] text-[--color-wolvio-dark]'}`}>
              {inv}
            </Link>
          ))}
        </div>
      </div>
      <ValidationReport result={result} />
    </div>
  )
}
